/**
 * Generating the painted instances of foliage layers from their density masks, and painting:
 * shared by the foliage brush and the MCP foliage tools.
 *
 * A region is regenerated by evaluating every candidate cell it touches with the shared rule of
 * helpers/foliagegen.ts and replacing the generated instances of exactly those cells, so nothing
 * outside changes. Layers without a place script are generated here on the main thread; the
 * ones with a script go to the scatter worker, which runs scripts sandboxed.
 */
import { Vector3 } from '@zephyr3d/base';
import { FOLIAGE_INSTANCE_STRIDE, foliageBrushWeight } from '@zephyr3d/scene';
import type { ClipmapTerrain, FoliageLayer, FoliageSystem } from '@zephyr3d/scene';
import { foliageCandidatePositions, generateFoliageRegion } from './foliagegen';
import type {
  FoliageGenContext,
  FoliageGenRegion,
  FoliageGenSettings,
  FoliageGenSurface
} from './foliagegen';
import { readWorldHeights } from './mcpterrain';
import { runScatterWorker } from './foliagescatterworker';

/** Most candidates one regeneration evaluates */
const MAX_CANDIDATES = 4_000_000;
const SCRIPT_TIMEOUT_MS = 60000;

function genSettings(layer: FoliageLayer): FoliageGenSettings {
  const g = layer.generation;
  return {
    spacing: g.spacing,
    scaleRange: g.scaleRange,
    slopeRange: g.slopeRange,
    heightRange: g.heightRange,
    yOffset: g.yOffset,
    randomYaw: g.randomYaw,
    seed: g.seed
  };
}

/** The surfaces of a layer: the terrain, or whatever collider lies below */
function surfaceSampler(foliage: FoliageSystem, layer: FoliageLayer, region: Readonly<FoliageGenRegion>) {
  const m = foliage.worldMatrix;
  const ox = m.m03;
  const oy = m.m13;
  const oz = m.m23;
  const result: FoliageGenSurface = { height: 0, slope: 0, normal: [0, 1, 0] };
  if (layer.generation.surface === 'terrain') {
    const terrain = foliage.terrain;
    const n = new Vector3();
    return (lx: number, lz: number): FoliageGenSurface | null => {
      const h = terrain?.getHeightAt(lx + ox, lz + oz) ?? null;
      if (h === null || !terrain!.getNormalAt(lx + ox, lz + oz, n)) {
        return null;
      }
      result.height = h;
      result.normal[0] = n.x;
      result.normal[1] = n.y;
      result.normal[2] = n.z;
      result.slope = (Math.acos(Math.min(1, Math.max(-1, n.y))) * 180) / Math.PI;
      return result;
    };
  }
  // Any surface: down from above the highest thing in the area, skipping the foliage's own colliders
  const world = foliage.scene?.physicsWorld ?? null;
  const top = Math.max(sceneTop(foliage, region), oy) + 1;
  const origin = new Vector3();
  const down = new Vector3(0, -1, 0);
  return (lx: number, lz: number): FoliageGenSurface | null => {
    if (!world) {
      return null;
    }
    origin.setXYZ(lx + ox, top, lz + oz);
    const hits = world.raycastAll(origin, down, Infinity);
    const hit = hits.find((h) => !foliage.ownsNode(h.node));
    if (!hit) {
      return null;
    }
    result.height = hit.point.y;
    result.normal[0] = hit.normal.x;
    result.normal[1] = hit.normal.y;
    result.normal[2] = hit.normal.z;
    result.slope = (Math.acos(Math.min(1, Math.max(-1, hit.normal.y))) * 180) / Math.PI;
    return result;
  };
}

/**
 * Brings the physics world up to date with the scene before raycasting. The editor does not
 * step the world, so colliders added, removed or moved since are not in it yet; this puts them
 * in and waits for mesh and terrain geometry.
 */
export async function prepareFoliagePhysics(foliage: FoliageSystem) {
  const world = foliage.scene?.physicsWorld;
  if (world) {
    world.syncWithScene();
    await world.whenReady();
  }
}

/** Whether a layer is regenerated in the worker or after waiting for physics, not synchronously */
export function foliageLayerIsAsync(layer: FoliageLayer) {
  return foliageLayerHasScript(layer) || layer.generation.surface === 'any';
}

/** Top of the scene, as a start height for rays looking for the ground */
function sceneTop(foliage: FoliageSystem, _region: Readonly<FoliageGenRegion>) {
  const box = foliage.scene?.boundingBox;
  return box && Number.isFinite(box.maxPoint.y) ? box.maxPoint.y : 1000;
}

/** Number of candidates a regeneration of a region evaluates */
export function countFoliageCandidates(layer: FoliageLayer, region: Readonly<FoliageGenRegion>) {
  const S = layer.generation.spacing;
  const cols = Math.ceil(region[2] / S) - Math.floor(region[0] / S);
  const rows = Math.ceil(region[3] / S) - Math.floor(region[1] / S);
  return Math.max(0, cols) * Math.max(0, rows);
}

/**
 * Regenerates the painted instances of a layer within a region, synchronously; for layers
 * without a place script. A layer on any surface raycasts the physics world as it is; call
 * {@link prepareFoliagePhysics} first, or use {@link regenerateFoliageRegion}.
 * @returns Number of instances now in the aligned region
 */
export function regenerateFoliageRegionSync(
  foliage: FoliageSystem,
  layerIndex: number,
  region: Readonly<FoliageGenRegion>
) {
  const layer = foliage.getLayer(layerIndex);
  if (!layer) {
    return 0;
  }
  if (countFoliageCandidates(layer, region) > MAX_CANDIDATES) {
    throw new Error('Too many candidates; raise the spacing of the layer or paint a smaller area');
  }
  const m = foliage.worldMatrix;
  const mask = layer.mask;
  const ctx: FoliageGenContext = {
    density: (lx, lz) => mask.sample(lx, lz),
    surface: surfaceSampler(foliage, layer, region),
    storeHeight: layer.generation.surface === 'any',
    originX: m.m03,
    originY: m.m13,
    originZ: m.m23
  };
  const result = generateFoliageRegion(genSettings(layer), region, ctx);
  foliage.replaceGeneratedInRegion(layerIndex, result.region, result.instances);
  return result.instances.length / FOLIAGE_INSTANCE_STRIDE;
}

/**
 * Regenerates the painted instances of a layer within a region, running its place script in
 * the scatter worker. The worker has no scene: for a terrain layer it samples the height grid,
 * for a layer on any surface the candidates are raycast here first and their surfaces sent.
 */
export async function regenerateFoliageRegionWithScript(
  foliage: FoliageSystem,
  layerIndex: number,
  region: Readonly<FoliageGenRegion>,
  heights?: Awaited<ReturnType<typeof readWorldHeights>>
) {
  const layer = foliage.getLayer(layerIndex);
  if (!layer) {
    return 0;
  }
  const onTerrain = layer.generation.surface === 'terrain';
  const terrain = foliage.terrain;
  if (onTerrain && !terrain?.heightMap) {
    return 0;
  }
  if (countFoliageCandidates(layer, region) > MAX_CANDIDATES) {
    throw new Error('Too many candidates; raise the spacing of the layer or paint a smaller area');
  }
  const settings = genSettings(layer);
  // The mask stays on the main thread: sample it at the candidates and send the values
  const cand = foliageCandidatePositions(settings, region);
  const n = cand.cols * cand.rows;
  const density = new Float32Array(n);
  for (let k = 0; k < n; k++) {
    density[k] = layer.mask.sample(cand.positions[2 * k], cand.positions[2 * k + 1]);
  }
  // So are the physics: raycast where a candidate could grow, and send what was found
  let surfaces: Float32Array | null = null;
  if (!onTerrain) {
    surfaces = new Float32Array(n * 5).fill(Number.NaN);
    const sample = surfaceSampler(foliage, layer, region);
    for (let k = 0; k < n; k++) {
      if (density[k] <= 0) {
        continue;
      }
      const sf = sample(cand.positions[2 * k], cand.positions[2 * k + 1]);
      if (sf) {
        surfaces.set([sf.height, sf.slope, sf.normal[0], sf.normal[1], sf.normal[2]], k * 5);
      }
    }
  }
  const area: FoliageGenRegion = [...cand.aligned];
  // Keep within the aligned cells, so the worker evaluates the same ones
  area[2] -= 1e-6;
  area[3] -= 1e-6;
  const m = foliage.worldMatrix;
  const h = onTerrain ? (heights ?? (await readWorldHeights(terrain!))) : null;
  const r = terrain?.worldRegion;
  const result = await runScatterWorker(
    {
      type: 'scatter',
      source: layer.generation.placeScript,
      entry: 'place',
      input: null,
      settings,
      area,
      origin: [m.m03, m.m13, m.m23],
      density,
      surfaces,
      storeHeight: !onTerrain,
      region: r ? [r.x, r.y, r.z, r.w] : [0, 0, 1, 1],
      // Transferred to the worker: a shared copy is cloned first
      heights: h ? (h === heights ? h.heights.slice() : h.heights) : new Float32Array(1),
      heightsWidth: h?.width ?? 1,
      heightsDepth: h?.depth ?? 1,
      avoid: new Float32Array(0),
      avoidRadius: 0,
      deadlineAt: Date.now() + SCRIPT_TIMEOUT_MS
    },
    SCRIPT_TIMEOUT_MS
  );
  if (foliage.disposed || foliage.getLayer(layerIndex) !== layer) {
    return 0;
  }
  foliage.replaceGeneratedInRegion(layerIndex, cand.aligned, result.instances);
  return result.instances.length / FOLIAGE_INSTANCE_STRIDE;
}

/** Whether a layer's regeneration needs the worker */
export function foliageLayerHasScript(layer: FoliageLayer) {
  return !!layer.generation.placeScript.trim();
}

/**
 * Regenerates the painted instances of a layer within a region, on the main thread or in the
 * worker as the layer needs, bringing the physics world up to date first for a layer on any
 * surface
 */
export async function regenerateFoliageRegion(
  foliage: FoliageSystem,
  layerIndex: number,
  region: Readonly<FoliageGenRegion>
) {
  const layer = foliage.getLayer(layerIndex);
  if (!layer) {
    return 0;
  }
  if (layer.generation.surface === 'any') {
    await prepareFoliagePhysics(foliage);
    if (foliage.getLayer(layerIndex) !== layer) {
      return 0;
    }
  }
  return foliageLayerHasScript(layer)
    ? regenerateFoliageRegionWithScript(foliage, layerIndex, region)
    : regenerateFoliageRegionSync(foliage, layerIndex, region);
}

/**
 * Regenerates every painted instance of a layer from its mask, e.g. after its generation
 * settings changed; with an empty mask the generated group is emptied
 */
export async function regenerateFoliageLayer(foliage: FoliageSystem, layerIndex: number) {
  const layer = foliage.getLayer(layerIndex);
  if (!layer) {
    return 0;
  }
  if (layer.generation.surface === 'any') {
    await prepareFoliagePhysics(foliage);
  }
  foliage.setInstances(layerIndex, [], 'generated');
  const tiles = layer.mask.getTileRegions();
  const heights =
    foliageLayerHasScript(layer) && foliage.terrain?.heightMap
      ? await readWorldHeights(foliage.terrain)
      : undefined;
  let total = 0;
  for (const tile of tiles) {
    total += foliageLayerHasScript(layer)
      ? await regenerateFoliageRegionWithScript(foliage, layerIndex, tile, heights)
      : regenerateFoliageRegionSync(foliage, layerIndex, tile);
  }
  return total;
}

/** A brush stamp */
export type FoliageBrushStamp = {
  /** Centre, local to the foliage system */
  x: number;
  z: number;
  radius: number;
  /** Change of the density at the centre, 0..1 */
  strength: number;
  /** Fraction of the radius over which the brush weight falls to 0 */
  falloff: number;
  erase: boolean;
  /** When erasing, whether the placed instances go too */
  erasePlaced: boolean;
};

/**
 * Applies one brush stamp to a layer: changes its mask and regenerates what it covers, and when
 * erasing placed instances too, thins those out by brush weight
 * @returns The region regenerated, local, or null when nothing changed
 */
export function applyFoliageBrushStamp(foliage: FoliageSystem, layerIndex: number, stamp: FoliageBrushStamp) {
  const layer = foliage.getLayer(layerIndex);
  if (!layer || !(stamp.radius > 0) || !(stamp.strength > 0)) {
    return null;
  }
  if (stamp.erase && stamp.erasePlaced) {
    foliage.eraseManualInstances(layerIndex, stamp.x, stamp.z, stamp.radius, stamp.strength, (t) =>
      foliageBrushWeight(t, stamp.falloff)
    );
  }
  return foliage.paintMask(
    layerIndex,
    stamp.x,
    stamp.z,
    stamp.radius,
    stamp.erase ? -stamp.strength : stamp.strength,
    stamp.falloff
  );
}

export { runScatterWorker };
export type { ClipmapTerrain };
