name: CI
on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.23.0

      - name: Rush Update
        run: node common/scripts/install-run-rush.js update

      - name: Rush Build
        run: node common/scripts/install-run-rush.js rebuild --verbose
